
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// 
//----------------------------------------------------

package Clases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int conjun_subor_causal = 34;
  public static final int interjeccion = 39;
  public static final int pro_personal = 12;
  public static final int ver_ing = 58;
  public static final int parentesiscerrado = 50;
  public static final int ver_irregular_pasadosimple = 17;
  public static final int interrogacionabierto = 45;
  public static final int pro_demostrativo = 14;
  public static final int coma = 42;
  public static final int admiracionabierto = 47;
  public static final int ver_irregular_pasadoparticipio = 18;
  public static final int advio_afirmacion = 24;
  public static final int conjun_subor_comparativa = 37;
  public static final int adj_indefinido = 9;
  public static final int guion = 53;
  public static final int conjun_coor_explicativa = 32;
  public static final int advio_tiempo = 20;
  public static final int conjun_coor_distributiva = 30;
  public static final int advio_duda = 26;
  public static final int advio_negacion = 25;
  public static final int preposicion = 27;
  public static final int pregunta = 56;
  public static final int corchetecerrado = 52;
  public static final int EOF = 0;
  public static final int art_indefinido = 11;
  public static final int adj_numeral_cardinal = 7;
  public static final int adj_posesivo = 4;
  public static final int error = 1;
  public static final int parentesisabierto = 49;
  public static final int adj_demostrativo = 5;
  public static final int contraccion = 40;
  public static final int pro_numeral = 13;
  public static final int advio_lugar = 21;
  public static final int punto = 41;
  public static final int advio_modo = 23;
  public static final int advio_cantidad = 22;
  public static final int dospuntos = 44;
  public static final int pro_interrogativo = 15;
  public static final int conjun_coor_adversativa = 29;
  public static final int adj_calificativo = 6;
  public static final int conjun_subor_consesiva = 36;
  public static final int conjun_subor_consecutiva = 35;
  public static final int adj_numeral_ordinal = 8;
  public static final int sustantivo = 2;
  public static final int ver_irregular_infinito = 16;
  public static final int interrogacioncerrado = 46;
  public static final int art_definido = 10;
  public static final int adjetivos = 3;
  public static final int corcheteabierto = 51;
  public static final int puntocoma = 43;
  public static final int asterisco = 54;
  public static final int admiracioncerrado = 48;
  public static final int verbo_regular = 19;
  public static final int conjun_coor_disyuntiva = 31;
  public static final int aux_futuro = 57;
  public static final int conjun_coor_copulativa = 28;
  public static final int conjun_subor_final = 38;
  public static final int diagonal = 55;
  public static final int conjun_subor_condicional = 33;
}

